### ISSUE TITLE
unexpected token export with python package

### ISSUE THREAD

**Issue by dedominicisfa** [stefanfreitag/cdk-budget-notifier#146]
by installing the package cdk-budget-notifier latest version and importing it, I have a jsii error. Something in the .tgz file which is in the python installed package, is preventing jsii to work correctly. I couldn't debug more

**Comment by stefanfreitag** [comment]
@dedominicisfa I was able to verify the issue locally. Can you try cdk-budget-notifier 0.3.3?

**Comment by dedominicisfa** [comment]
It worked thanks

Le ven. 2 avr. 2021 à 21:29, Stefan Freitag ***@***.***> a
écrit :

**Comment by stefanfreitag** [comment]
Closing - upgrade to latest version resolved the issue.

**Comment by stefanfreitag** [comment]
@all-contributors please add @dedominicisfa  for bug.
