### ISSUE TITLE
Why more than one NPM package?

### ISSUE THREAD

**Issue by coltenkrauter** [stefanfreitag/cdk-budget-notifier#170]
While looking for a `cdk budget notifier`, I found two that appear to be yours. 
Is there a reason to have more than one? 

https://www.npmjs.com/package/aws_budget_notifier
https://www.npmjs.com/package/@stefanfreitag/aws-budget-notifier

Thanks!

**Comment by stefanfreitag** [comment]
No, I updated [@stefanfreitag/aws-budget-notifier](https://www.npmjs.com/package/@stefanfreitag/aws-budget-notifier) and marked it as deprecated.

**Comment by coltenkrauter** [comment]
Sounds good, thanks 🙏
